/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <android/log.h>
#include <opencv2/opencv.hpp>
#include <vector>

using namespace std;
using namespace cv;

/* Header for class com_mokdoryeong_team7_mokdoryeong_OpencvRoutine */


#ifndef _Included_com_mokdoryeong_team7_mokdoryeong_OpencvRoutine
#define _Included_com_mokdoryeong_team7_mokdoryeong_OpencvRoutine
#ifdef __cplusplus
extern "C" {
#endif


void detectNonfrontalFace(Mat& frame, int& x1, int& y1, int& x2, int& y2);

JNIEXPORT jintArray JNICALL Java_com_mokdoryeong_team7_mokdoryeong_OpencvRoutine_nonFrontalFaceDetection
(JNIEnv*, jclass, jlong, jint, jint, jint, jint);

JNIEXPORT jintArray JNICALL Java_com_mokdoryeong_team7_mokdoryeong_OpencvRoutine_detectNeckPoints
        (JNIEnv*, jclass, jlong, jint, jint, jint, jint);


#ifdef __cplusplus
}
#endif
#endif
